---
version: 2

updates:
  - package-ecosystem: "maven"
    target-branch: "master"
    registries: "*"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
