---
# yamllint disable rule:line-length
# Automatically runs on PRs to ensure the changes meet requirements and pass tests.
name: PR Validation

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          check-latest: false

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Resolve plugins
        run: mvn dependency:resolve-plugins

      # dependency:analyze-only is run during the main build, but they sometimes catch different things
      - name: Run dependency analysis
        run: mvn dependency:analyze

      - name: Build and verify
        run: mvn verify
